version: "3"
services:
  redis:
    image: redis-nest-queue:local-0
    container_name: redis-local-0
    build:
      context: ./.docker
    ports:
      - 7000:7000
    command: "--port 7000 --requirepass redisPassword --appendonly yes --appendfsync no"
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - local-network
volumes:
  redis:
    name: redis-storage
networks:
  local-network:
    driver: bridge